# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.6.3"

before_script:
 - apt-get update && apt-get install -y sshpass

deploy_stage:
  stage: deploy
  environment: Staging
  only:
    - master
  script:
    - export SSHPASS=$USER_PASS 
    - sshpass -e scp -o stricthostkeychecking=no -r . username@host:path